# Generated by Django 4.1.6 on 2023-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('id_district', models.IntegerField(verbose_name='Район')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name_district', models.CharField(max_length=60, verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('id_district', models.IntegerField(verbose_name='Район')),
                ('number_floors', models.IntegerField(verbose_name='Количество этажей')),
                ('number_sell_floor', models.IntegerField(verbose_name='номер этажа')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
    ]
